// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user3.proto

package com.distSCA.service3_calorie;

public interface CalculateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3_calorie.CalculateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float number1 = 1;</code>
   */
  float getNumber1();

  /**
   * <code>float number2 = 2;</code>
   */
  float getNumber2();

  /**
   * <code>.service3_calorie.CalculateRequest.Operation operation = 3;</code>
   */
  int getOperationValue();
  /**
   * <code>.service3_calorie.CalculateRequest.Operation operation = 3;</code>
   */
  com.distSCA.service3_calorie.CalculateRequest.Operation getOperation();
}
