// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user3.proto

package com.distSCA.service3_calorie;

public interface ConvertResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3_calorie.ConvertResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string number = 1;</code>
   */
  java.lang.String getNumber();
  /**
   * <code>string number = 1;</code>
   */
  com.google.protobuf.ByteString
      getNumberBytes();

  /**
   * <code>int32 base = 2;</code>
   */
  int getBase();
}
