// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user3.proto

package com.distSCA.service3_calorie;

public final class MathServiceImpl {
  private MathServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_calorie_ConvertMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_calorie_ConvertMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_calorie_ConvertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_calorie_ConvertResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_calorie_RandomRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_calorie_RandomRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_calorie_NumberResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_calorie_NumberResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_calorie_CalculateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_calorie_CalculateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_calorie_CalculateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_calorie_CalculateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_calorie_NumberMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_calorie_NumberMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013user3.proto\022\020service3_calorie\"B\n\016Conve" +
      "rtMessage\022\016\n\006number\030\001 \001(\t\022\020\n\010fromBase\030\002 " +
      "\001(\005\022\016\n\006toBase\030\003 \001(\005\"/\n\017ConvertResponse\022\016" +
      "\n\006number\030\001 \001(\t\022\014\n\004base\030\002 \001(\005\":\n\rRandomRe" +
      "quest\022\017\n\007numbers\030\001 \001(\005\022\013\n\003min\030\002 \001(\005\022\013\n\003m" +
      "ax\030\003 \001(\005\" \n\016NumberResponse\022\016\n\006number\030\001 \001" +
      "(\005\"\303\001\n\020CalculateRequest\022\017\n\007number1\030\001 \001(\002" +
      "\022\017\n\007number2\030\002 \001(\002\022?\n\toperation\030\003 \001(\0162,.s" +
      "ervice3_calorie.CalculateRequest.Operati" +
      "on\"L\n\tOperation\022\014\n\010ADDITION\020\000\022\017\n\013SUBTRAC" +
      "TION\020\001\022\022\n\016MULTIPLICATION\020\002\022\014\n\010DIVISION\020\003" +
      "\"4\n\021CalculateResponse\022\016\n\006result\030\001 \001(\002\022\017\n" +
      "\007message\030\002 \001(\t\"\037\n\rNumberMessage\022\016\n\006numbe" +
      "r\030\001 \001(\0022\372\002\n\013MathService\022V\n\tcalculate\022\".s" +
      "ervice3_calorie.CalculateRequest\032#.servi" +
      "ce3_calorie.CalculateResponse\"\000\022^\n\025gener" +
      "ateRandomNumbers\022\037.service3_calorie.Rand" +
      "omRequest\032 .service3_calorie.NumberRespo" +
      "nse\"\0000\001\022Y\n\raverageValues\022\037.service3_calo" +
      "rie.NumberMessage\032#.service3_calorie.Cal" +
      "culateResponse\"\000(\001\022X\n\013convertBase\022 .serv" +
      "ice3_calorie.ConvertMessage\032!.service3_c" +
      "alorie.ConvertResponse\"\000(\0010\001B1\n\034com.dist" +
      "SCA.service3_calorieB\017MathServiceImplP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service3_calorie_ConvertMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service3_calorie_ConvertMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_calorie_ConvertMessage_descriptor,
        new java.lang.String[] { "Number", "FromBase", "ToBase", });
    internal_static_service3_calorie_ConvertResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service3_calorie_ConvertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_calorie_ConvertResponse_descriptor,
        new java.lang.String[] { "Number", "Base", });
    internal_static_service3_calorie_RandomRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service3_calorie_RandomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_calorie_RandomRequest_descriptor,
        new java.lang.String[] { "Numbers", "Min", "Max", });
    internal_static_service3_calorie_NumberResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service3_calorie_NumberResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_calorie_NumberResponse_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_service3_calorie_CalculateRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service3_calorie_CalculateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_calorie_CalculateRequest_descriptor,
        new java.lang.String[] { "Number1", "Number2", "Operation", });
    internal_static_service3_calorie_CalculateResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service3_calorie_CalculateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_calorie_CalculateResponse_descriptor,
        new java.lang.String[] { "Result", "Message", });
    internal_static_service3_calorie_NumberMessage_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_service3_calorie_NumberMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_calorie_NumberMessage_descriptor,
        new java.lang.String[] { "Number", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
