// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user3.proto

package com.distSCA.service3_calorie;

public interface NumberResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3_calorie.NumberResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   */
  int getNumber();
}
