// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user2.proto

package com.distSCA.service2_prox;

public interface ConvertResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ConvertResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string number = 1;</code>
   */
  java.lang.String getNumber();
  /**
   * <code>string number = 1;</code>
   */
  com.google.protobuf.ByteString
      getNumberBytes();

  /**
   * <code>int32 base = 2;</code>
   */
  int getBase();
}
