// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user2.proto

package com.distSCA.service2_prox;

public interface NumberResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NumberResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   */
  int getNumber();
}
