// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user2.proto

package com.distSCA.service2_prox;

public interface NumberMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NumberMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float number = 1;</code>
   */
  float getNumber();
}
